# Generated by Django 3.1.7 on 2021-04-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20210408_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='note',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='note',
            name='theme',
            field=models.CharField(choices=[('bg-primary', 'Blue'), ('bg-success', 'Vert'), ('bg-warning', 'Jaune'), ('bg-dark', 'Noir'), ('bg-pink', 'Violet'), ('bg-danger', 'Rouge')], max_length=15),
        ),
        migrations.DeleteModel(
            name='NoteMember',
        ),
    ]
