# Generated by Django 3.1.7 on 2021-03-30 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(db_index=True, editable=False, max_length=20, null=True)),
                ('callid', models.CharField(blank=True, db_index=True, editable=False, max_length=32)),
                ('queue', models.CharField(blank=True, db_column='queuename', db_index=True, editable=False, max_length=32)),
                ('agent', models.CharField(blank=True, db_index=True, editable=False, max_length=32)),
                ('event', models.CharField(blank=True, db_index=True, editable=False, max_length=32)),
                ('data', models.TextField(blank=True, editable=False)),
            ],
            options={
                'db_table': 'queues_log',
            },
        ),
        migrations.AlterField(
            model_name='queue',
            name='context',
            field=models.ForeignKey(db_column='context', default=1, max_length=200, on_delete=django.db.models.deletion.CASCADE, to='pbx.contexts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sippeers',
            name='allow',
            field=models.CharField(default='all', help_text='codecs autorisés', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sippeers',
            name='deny',
            field=models.CharField(blank=True, default='0.0.0.0/0', help_text='sous-réseaux interdits', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='sippeers',
            name='mailbox',
            field=models.CharField(help_text='101@default', max_length=40),
        ),
        migrations.AlterField(
            model_name='sippeers',
            name='permit',
            field=models.CharField(blank=True, default='0.0.0.0/0', help_text='sous-réseaux autorisés', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='sippeers',
            name='transport',
            field=models.CharField(blank=True, choices=[('udp', 'udp'), ('tcp', 'tcp'), ('udp,tcp', 'udp,tcp'), ('tcp,udp', 'tcp,udp')], help_text='Transport des données', max_length=40, null=True),
        ),
    ]
