# Generated by Django 3.1.7 on 2021-03-31 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbx', '0002_auto_20210330_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contexts',
            name='full_name',
            field=models.CharField(max_length=25, verbose_name='la description'),
        ),
        migrations.AlterField(
            model_name='contexts',
            name='name',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='le contexte'),
        ),
    ]
