# Generated by Django 3.1.7 on 2021-03-31 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbx', '0003_auto_20210331_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ps_auths',
            name='auth_type',
            field=models.CharField(blank=True, default='userpass', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ps_auths',
            name='password',
            field=models.CharField(max_length=80),
        ),
    ]
