# Generated by Django 3.1.7 on 2021-04-04 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbx', '0004_auto_20210331_0628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asteriskpublication',
            options={'verbose_name': 'Ps_asterisk_publications', 'verbose_name_plural': 'Ps_asterisk_publications'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Ps_contacts', 'verbose_name_plural': 'Ps_contacts'},
        ),
        migrations.AlterModelOptions(
            name='contexts',
            options={'verbose_name': 'Context', 'verbose_name_plural': 'Contexts'},
        ),
        migrations.AlterModelOptions(
            name='endpoints',
            options={'verbose_name': 'Ps_endpoints', 'verbose_name_plural': 'Ps_endpoints'},
        ),
        migrations.AlterModelOptions(
            name='endpoints_id_ips',
            options={'verbose_name': 'Ps_endpoint_id_ips', 'verbose_name_plural': 'Ps_endpoint_id_ips'},
        ),
        migrations.AlterModelOptions(
            name='extensions',
            options={'verbose_name': 'Extension', 'verbose_name_plural': 'Extensions'},
        ),
        migrations.AlterModelOptions(
            name='ivrdetails',
            options={'verbose_name': 'Ivr_details', 'verbose_name_plural': 'Ivr_details'},
        ),
        migrations.AlterModelOptions(
            name='ps_aors',
            options={'verbose_name': 'Ps_aor', 'verbose_name_plural': 'Ps_aors'},
        ),
        migrations.AlterModelOptions(
            name='ps_auths',
            options={'verbose_name': 'Ps_auth', 'verbose_name_plural': 'Ps_auths'},
        ),
        migrations.AlterModelOptions(
            name='queue',
            options={'verbose_name': 'Queues', 'verbose_name_plural': 'Queues'},
        ),
        migrations.AlterModelOptions(
            name='queuemember',
            options={'verbose_name': 'Queue_members', 'verbose_name_plural': 'Queue_members'},
        ),
        migrations.AlterModelOptions(
            name='queuerules',
            options={'verbose_name': 'Queues_rules', 'verbose_name_plural': 'Queues_rules'},
        ),
        migrations.AlterModelOptions(
            name='sippeers',
            options={'verbose_name': 'Sippeers', 'verbose_name_plural': 'Sippeers'},
        ),
    ]
