# Generated by Django 3.1.7 on 2021-04-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbx', '0005_auto_20210404_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ps_auths',
            name='username',
            field=models.CharField(help_text='101', max_length=40),
        ),
    ]
