

# CHOICES = [(i, i) for i in range(11)]

APPS = (
    ("Dial", u"(Dial) Compose le numéro"),
    ("HangUp", u"(HangUp) Posez le téléphone"),
    ("Wait", u"(Wait) Attendez x secondes"),
    ("Answer", u"(Answer) Décrocher le téléphone"),
    ("AddQueueMember", u"AddQueueMember (file d'attente, canal) Supprimer du groupe"),
    ("Queue", u"Queue (queue_name) Aller à la file d'attente"),
    ("PlayBack", u"(PlayBack) Lire le fichier son"),
    ("Set", u"(Set) Définir la variable"),
    ("Read", u"(Read) Lisez le clav en changement."),
    ("BackGround", u"(BackGround) Jouez le son et attendez prolongé"),
    ("Bridge", u"(Bridge) Faire un pont de 2 canaux"),
    ("Busy", u"(Busy) Retour occupé"),
    ("ChangeMonitor", u"(ChangeMonitor) Tour. surveiller le fichier de canal"),
    ("Congestion", u"(Congestion) Direction surchargée"),
    ("DBdel", u"(DBdel) Supprimer la clé de int. DB"),
    ("DBdeltree", u"(DBdeltree) Supprimer l'arbre de l'ext. DB"),
    ("Echo", u"(Echo) Jouer audible"),
    ("ConfBridge", u"(ConfBridge) Créer un pont de conférence"),
    ("Exec", u"(Exec) Exécutez adj. plan de numérotation"),
    ("ExecIf", u"(ExecIf) Exécutez si"),
    ("ExecIfTime", u"(ExecIfTime) Exécuter if + time"),
    ("GoSub",
     u"GoSub([[context|]extension|]priority) Aller à l'extension puis revenir"),
    ("GoTo", u"GoTo([[context|]extension|]priority) Aller à l'extension"),
    ("GoToIf", u"GoToIf(condition?context1,extension1,priority1:context2,extension2,priority2)"),
    ("GotoIfTime", u"(GotoIfTime) Allez ext. si + temps"),
    ("ImportVar", u"(ImportVar) Importer une variable dans une nouvelle"),
    ("Incomplete", u"(Incomplete) Revenir insatisfait"),
    ("Macro", u"(Macro) Exécuter la macro"),
    ("MacroExclusive", u"(MacroExclusive) Exécuter. une seule macro"),
    ("MacroIf", u"(MacroIf) Macro si"),
    ("Monitor", u"(Monitor) Surveillance des canaux"),
    ("StopMonitor", u"(StopMonitor) Arrêter la surveillance des canaux"),
    ("MSet", u"(MSet) Const. variables de canal"),
    ("MusicOnHold", u"(MusicOnHold)Écouter de la musique en attente"),
    ("NoCDR", u"(NoCDR) N'écrivez pas de CDR"),
    ("NoOp", u"(NoOp) Rien à faire"),
    ("Park", u"(Park) se garer"),
    ("MeetMeChannelAdmin", u"(MeetMeChannelAdmin) Administration des canaux"),
    ("ParkedCall", u"(ParkedCall) Répondre à garé"),
    ("PauseMonitor", u"(PauseMonitor) Mettre le moniteur en pause"),
    ("Proceeding", u"(Proceeding) L'appel est passé"),
    ("Progress", u"(Progress) Appel en cours"),
    ("RaiseException", u"(RaiseException) Lancer une exception"),
    ("ReadExten", u"(ReadExten) Lire le numéro depuis AC"),
    ("ReadFile", u"(ReadFile) Autre fichier en perm. canaliser"),
    ("MeetMeAdmin", u"(MeetMeAdmin) Administration de la salle"),
    ("Record", u"(Record) Ecrire un fichier"),
    ("ResetCDR", u"(ResetCDR) Réinitialiser le CDR"),
    ("RetryDial", u"(RetryDial) Recomposer en cas d'échec"),
    ("RemoveQueueMember", u"RemoveQueueMember(queue,channel) Ajouter au groupe"),
    ("Ringing", u"(Ringing) Le téléphone sonne"),
    ("SayAlpha", u"(SayAlpha) Dites à Alpha"),
    ("SayDigits", u"(SayDigits) Énoncez les nombres"),
    ("SayNumber", u"(SayNumber) Numéro de conversation"),
    ("SayPhonetic", u"(SayPhonetic) Parlez phonétiquement"),
    ("SendFAX", u"(SendFAX) Envoyer un fax"),
    ("ReceiveFAX", u"(ReceiveFAX) Recevoir un fax"),
    ("SetAMAFlags", u"(SetAMAFlags) Définir le drapeau AMA"),
    ("SetCallerPres", u"(SetCallerPres) Définir l'affichage de l'ID de l'appelant"),
    ("SetMusicOnHold", u"(SetMusicOnHold) Installez des muses. attentes"),
    ("SIPAddHeader", u"(SIPAddHeader) Âge. ish. zag. sip package"),
    ("SIPDtmfMode", u"(SIPDtmfMode) Changer le mode DTMF"),
    ("SIPRemoveHeader", u"(SIPRemoveHeader) Ud. ish. zag. sip package"),
    ("StartMusicOnHold", u"(StartMusicOnHold) Commencez à jouer à MOH"),
    ("MeetMeCount", u"(MeetMeCount) Contrer"),
    ("Transfer", u"(Transfer) Transférer un appel vers un numéro"),
    ("TryExec", u"(TryExec) Essayez d'exécuter"),
    ("TrySystem", u"(TrySystem) Essayez d'exécuter. UNIX"),
    ("System", u"(System) Exécuter la commande UNIX"),
    ("UnpauseMonitor", u"(UnpauseMonitor) Réactiver le moniteur"),
    ("WaitExten", u"(WaitExten) Attendez un autre"),
    ("WaitMusicOnHold", u"(WaitMusicOnHold) Attendez l'ajout. jouer à MOH"),
    ("MeetMe", u"(MeetMe) Application de conférence"),
    ("SLAStation", u"(SLAStation) Exécuter la ligne partagée"),
    ("SLATrunk", u"(SLATrunk) Apparence de ligne partagée"),
)

MUSICONHOLD = (
    ('ring 1', 'ring 1'),
    ('ring 2', 'ring 2'),
    ('ring 3', 'ring 3'),
    ('ring 4', 'ring 4'),
    ('ring 5', 'ring 5'),
    ('ring 6', 'ring 6'),
    ('ring 7', 'ring 7'),
    ('ring 8', 'ring 8'),
    ('ring 9', 'ring 9'),
    ('ring 10', 'ring 10'),
)